import type { ProgramOverview, ProjectDetail, ProjectSummary } from "./types";

const projects: ProjectSummary[] = [
  {
    id: "meridian-heights",
    code: "MH-042",
    name: "Meridian Heights",
    location: "Worli, Mumbai",
    region: "West",
    phase: "Structure",
    status: "on-track",
    progress: 68,
    plannedProgress: 66,
    openIssues: 3,
    criticalIssues: 0,
    callsCompleted: 5,
    callsExpected: 5,
    reportStatus: "sent",
    updatedAt: "17 Aug · 18:42",
    manager: "Arjun Mehta",
    nextMilestone: "Tower B top-out",
    nextMilestoneDate: "29 Aug",
    accent: "#315c4c",
  },
  {
    id: "north-gate",
    code: "NG-118",
    name: "North Gate Business Park",
    location: "Sector 62, Gurugram",
    region: "North",
    phase: "MEP",
    status: "at-risk",
    progress: 47,
    plannedProgress: 56,
    openIssues: 8,
    criticalIssues: 2,
    callsCompleted: 4,
    callsExpected: 6,
    reportStatus: "drafting",
    updatedAt: "17 Aug · 18:28",
    manager: "Neha Kapoor",
    nextMilestone: "HVAC pressure test",
    nextMilestoneDate: "21 Aug",
    accent: "#ba4935",
  },
  {
    id: "riverstone-villas",
    code: "RV-207",
    name: "Riverstone Villas",
    location: "Hinjawadi, Pune",
    region: "West",
    phase: "Finishes",
    status: "watch",
    progress: 82,
    plannedProgress: 85,
    openIssues: 5,
    criticalIssues: 1,
    callsCompleted: 3,
    callsExpected: 5,
    reportStatus: "awaiting-calls",
    updatedAt: "17 Aug · 17:56",
    manager: "Rohan Deshpande",
    nextMilestone: "Clubhouse handover",
    nextMilestoneDate: "25 Aug",
    accent: "#b47c2d",
  },
  {
    id: "atlas-logistics",
    code: "AL-084",
    name: "Atlas Logistics Hub",
    location: "Devanahalli, Bengaluru",
    region: "South",
    phase: "Mobilisation",
    status: "on-track",
    progress: 21,
    plannedProgress: 19,
    openIssues: 2,
    criticalIssues: 0,
    callsCompleted: 4,
    callsExpected: 4,
    reportStatus: "sent",
    updatedAt: "17 Aug · 18:10",
    manager: "Isha Nair",
    nextMilestone: "Piling complete",
    nextMilestoneDate: "04 Sep",
    accent: "#44667e",
  },
];

const meridian: ProjectDetail = {
  ...projects[0],
  client: "Aster Urban Developments",
  contractor: "Mavrik Buildcon Pvt. Ltd.",
  contractValue: "₹186 Cr",
  startDate: "12 Jan 2025",
  targetDate: "18 Mar 2027",
  workingDaysElapsed: 411,
  workingDaysTotal: 612,
  weather: { condition: "Light rain", temperature: "28°C", impact: "45 min concrete delay" },
  progressHistory: [
    { label: "Mar", actual: 37, planned: 40 },
    { label: "Apr", actual: 44, planned: 45 },
    { label: "May", actual: 51, planned: 50 },
    { label: "Jun", actual: 57, planned: 56 },
    { label: "Jul", actual: 63, planned: 61 },
    { label: "Aug", actual: 68, planned: 66 },
  ],
  memory: [
    "Tower B slab cycle has held at 8 days for three consecutive floors.",
    "Facade bracket deliveries normally arrive on Tuesdays; the 12 Aug batch was short by 180 units.",
    "Rain disruption has accumulated to 7.5 hours this month, still inside the 12-hour allowance.",
  ],
  brain: [
    { id: "fact-1", kind: "risk", statement: "West elevation facade work will stop after Wednesday unless 180 balance brackets arrive.", owner: "Vikram Shah", dueDate: "19 Aug", status: "active", confidence: 96, observedAt: "Today · 18:12", sourceType: "voice", sourceLabel: "Arjun Mehta call", evidenceCount: 3 },
    { id: "fact-2", kind: "commitment", statement: "Procurement will confirm the facade bracket recovery date by noon tomorrow.", owner: "Arjun Mehta", dueDate: "18 Aug", status: "active", confidence: 91, observedAt: "Today · 17:34", sourceType: "whatsapp", sourceLabel: "Meridian Site Updates", evidenceCount: 2 },
    { id: "fact-3", kind: "progress", statement: "Tower B maintained an eight-day slab cycle for three consecutive floors.", owner: "Vikram Shah", status: "active", confidence: 98, observedAt: "Today · 18:09", sourceType: "dpr", sourceLabel: "DPR · 17 Aug", evidenceCount: 8 },
    { id: "fact-4", kind: "decision", statement: "Hoist 02 remains isolated until the vendor technician signs the inspection sheet.", owner: "Dinesh Yadav", dueDate: "18 Aug", status: "active", confidence: 99, observedAt: "Today · 18:23", sourceType: "voice", sourceLabel: "Dinesh Yadav call", evidenceCount: 2 },
    { id: "fact-5", kind: "issue", statement: "Level 19 electrical riser clearance differs by 75 mm between MEP and structural drawings.", owner: "Sana Mirza", dueDate: "20 Aug", status: "active", confidence: 97, observedAt: "Yesterday · 16:46", sourceType: "whatsapp", sourceLabel: "Tower B Coordination", evidenceCount: 4 },
    { id: "fact-6", kind: "safety", statement: "Wet east access route was barricaded, inspected, and reopened after the rain hold.", owner: "Dinesh Yadav", status: "resolved", confidence: 94, observedAt: "Today · 15:20", sourceType: "whatsapp", sourceLabel: "Safety & Logistics", evidenceCount: 2 },
  ],
  sourceCounts: { voice: 74, whatsapp: 1248, dpr: 19 },
  team: [
    { id: "p-101", name: "Arjun Mehta", role: "Project Manager", phoneMasked: "+91 ••••• 2417", initials: "AM", callTime: "18:00", lastCallStatus: "completed", lastCallAt: "18:12", responseStreak: 14 },
    { id: "p-102", name: "Vikram Shah", role: "Civil Lead", phoneMasked: "+91 ••••• 8842", initials: "VS", callTime: "18:05", lastCallStatus: "completed", lastCallAt: "18:09", responseStreak: 11 },
    { id: "p-103", name: "Sana Mirza", role: "MEP Lead", phoneMasked: "+91 ••••• 5031", initials: "SM", callTime: "18:10", lastCallStatus: "completed", lastCallAt: "18:18", responseStreak: 9 },
    { id: "p-104", name: "Dinesh Yadav", role: "Safety Officer", phoneMasked: "+91 ••••• 7790", initials: "DY", callTime: "18:15", lastCallStatus: "completed", lastCallAt: "18:23", responseStreak: 18 },
    { id: "p-105", name: "Kabir Jain", role: "Planning Engineer", phoneMasked: "+91 ••••• 1264", initials: "KJ", callTime: "18:20", lastCallStatus: "completed", lastCallAt: "18:31", responseStreak: 7 },
  ],
  issues: [
    {
      id: "iss-401",
      title: "Facade brackets short by 180 units",
      description: "Latest delivery covers only the east elevation through Level 24. West elevation work may stop after Wednesday.",
      category: "material",
      severity: "high",
      status: "open",
      owner: "Vikram Shah",
      raisedBy: "Vikram Shah",
      raisedAt: "15 Aug 2026",
      dueDate: "19 Aug 2026",
      ageDays: 2,
      impactedActivity: "Tower A facade — L22–L24",
    },
    {
      id: "iss-402",
      title: "RFI-118: electrical riser clearance",
      description: "MEP and structural drawings differ by 75 mm at the Level 19 riser. Consultant confirmation is pending.",
      category: "design",
      severity: "medium",
      status: "monitoring",
      owner: "Sana Mirza",
      raisedBy: "Sana Mirza",
      raisedAt: "16 Aug 2026",
      dueDate: "20 Aug 2026",
      ageDays: 1,
      impactedActivity: "Tower B riser installation",
    },
    {
      id: "iss-403",
      title: "Hoist 02 intermittent limit-switch fault",
      description: "The service hoist stopped twice during the afternoon shift. Vendor technician is booked for morning inspection.",
      category: "equipment",
      severity: "medium",
      status: "open",
      owner: "Arjun Mehta",
      raisedBy: "Dinesh Yadav",
      raisedAt: "17 Aug 2026",
      dueDate: "18 Aug 2026",
      ageDays: 0,
      impactedActivity: "Vertical material movement",
    },
  ],
  milestones: [
    { id: "m-1", name: "Tower A top-out", plannedDate: "02 Aug", forecastDate: "31 Jul", progress: 100, status: "complete" },
    { id: "m-2", name: "Tower B top-out", plannedDate: "29 Aug", forecastDate: "28 Aug", progress: 78, status: "on-track" },
    { id: "m-3", name: "Facade watertight", plannedDate: "16 Oct", forecastDate: "20 Oct", progress: 43, status: "watch" },
    { id: "m-4", name: "MEP first fix", plannedDate: "05 Dec", forecastDate: "05 Dec", progress: 31, status: "on-track" },
  ],
  calls: [
    {
      id: "call-1001",
      contactName: "Arjun Mehta",
      role: "Project Manager",
      status: "completed",
      startedAt: "18:12",
      durationSeconds: 284,
      sentiment: "positive",
      summary: "Structure remains ahead of baseline. Escalated facade bracket shortage and requested procurement confirmation by noon tomorrow.",
      transcript: [
        { role: "agent", message: "Good evening Arjun. What was completed at Meridian Heights today?", at: "00:08" },
        { role: "user", message: "Tower B Level 26 slab reinforcement is complete and the pour starts at six tomorrow morning. Tower A blockwork closed another eleven rooms.", at: "00:18" },
        { role: "agent", message: "Yesterday you expected the facade bracket batch. Did it arrive in full?", at: "00:43" },
        { role: "user", message: "It arrived short by 180 brackets. We can work until Wednesday, then the west elevation stops unless procurement recovers it.", at: "00:52" },
      ],
      answers: {
        completed: "Tower B L26 reinforcement complete; Tower A blockwork closed in 11 rooms.",
        challenges: "Facade bracket delivery was short by 180 units.",
        tomorrow: "Begin L26 concrete pour at 06:00 and continue Tower A blockwork.",
        blockers: "West elevation facade work stops after Wednesday without balance brackets.",
        safety: "No incidents; hoist 02 requires vendor inspection before use.",
      },
    },
    {
      id: "call-1002",
      contactName: "Vikram Shah",
      role: "Civil Lead",
      status: "completed",
      startedAt: "18:09",
      durationSeconds: 231,
      sentiment: "neutral",
      summary: "Concrete and blockwork targets met. Crew will shift to core shuttering after the morning pour.",
      transcript: [],
      answers: {
        completed: "L26 reinforcement and east core shutter checks completed.",
        challenges: "Forty-five-minute rain hold affected the afternoon lift plan.",
        tomorrow: "L26 pour and L27 core shutter mobilisation.",
        blockers: "No civil blocker for tomorrow.",
        safety: "Wet access route was barricaded and reopened after inspection.",
      },
    },
    {
      id: "call-1003",
      contactName: "Sana Mirza",
      role: "MEP Lead",
      status: "completed",
      startedAt: "18:18",
      durationSeconds: 318,
      sentiment: "concerned",
      summary: "Riser installation is paused at Level 19 pending consultant clarification on a 75 mm clearance conflict.",
      transcript: [],
      answers: {
        completed: "Pressure testing completed for Tower A Levels 14–16.",
        challenges: "Level 19 electrical riser clearance conflicts with structural drawing.",
        tomorrow: "Close pressure-test punch points and route services at Level 18.",
        blockers: "RFI-118 response needed before Level 19 riser installation.",
        safety: "No MEP safety observations.",
      },
    },
    {
      id: "call-1004",
      contactName: "Dinesh Yadav",
      role: "Safety Officer",
      status: "completed",
      startedAt: "18:23",
      durationSeconds: 196,
      sentiment: "neutral",
      summary: "No incidents or near misses. Hoist 02 was isolated after repeat limit-switch trips.",
      transcript: [],
      answers: {
        completed: "Two toolbox talks and 46 scaffold tags audited.",
        challenges: "Hoist 02 tripped twice and was isolated.",
        tomorrow: "Vendor inspection and lifting-plan review before concrete pour.",
        blockers: "Hoist must remain isolated until technician sign-off.",
        safety: "Zero incidents; 96% PPE compliance across 184 workers.",
      },
    },
    {
      id: "call-1005",
      contactName: "Kabir Jain",
      role: "Planning Engineer",
      status: "completed",
      startedAt: "18:31",
      durationSeconds: 247,
      sentiment: "positive",
      summary: "Two-day structural lead remains intact. Facade recovery plan will be reflected after procurement confirmation.",
      transcript: [],
      answers: {
        completed: "Updated four-week lookahead and reconciled daily quantities.",
        challenges: "Facade material shortfall may consume two days of float.",
        tomorrow: "Issue revised micro-schedule after supplier confirmation.",
        blockers: "Supplier recovery date required by noon.",
        safety: "No planning-related safety item.",
      },
    },
  ],
  latestReport: {
    id: "dpr-mh-2026-08-17",
    projectId: "meridian-heights",
    date: "17 August 2026",
    status: "sent",
    sentAt: "18:42",
    recipients: ["projects@asterurban.in", "ops@mavrikbuildcon.in"],
    executiveSummary: "Structure remains 2% ahead of plan with the Tower B Level 26 pour ready for 06:00. The principal schedule exposure is a shortage of 180 facade brackets; procurement confirmation is required by noon to protect the west-elevation sequence. No incidents were reported across 184 workers.",
    workCompleted: [
      "Tower B Level 26 reinforcement completed and cleared for concrete.",
      "Tower A blockwork completed in 11 rooms.",
      "MEP pressure testing completed across Levels 14–16.",
      "46 scaffold tags audited; two toolbox talks delivered.",
    ],
    plannedTomorrow: [
      "Start Tower B Level 26 concrete pour at 06:00.",
      "Mobilise core shuttering for Level 27.",
      "Close MEP pressure-test punch points and issue the revised four-week lookahead.",
    ],
    blockers: [
      "180 facade brackets outstanding; west elevation has two working days of stock.",
      "RFI-118 consultant response required for Level 19 electrical riser.",
      "Hoist 02 held out of service pending vendor sign-off.",
    ],
    safetyNotes: ["Zero incidents or near misses.", "96% observed PPE compliance.", "Hoist 02 isolated after two limit-switch trips."],
    manpower: 184,
    callsIncluded: 5,
    callsExpected: 5,
    weather: "Light rain · 45-minute impact",
  },
};

function projectFromTemplate(summary: ProjectSummary, index: number): ProjectDetail {
  const open = Math.max(1, summary.openIssues);
  return {
    ...meridian,
    ...summary,
    client: ["Korus Commercial", "Sierra Living", "Nexus Industrial"][index - 1] ?? meridian.client,
    contractor: ["Northspan Projects", "Terra Habitat", "Axis Infraworks"][index - 1] ?? meridian.contractor,
    contractValue: ["₹244 Cr", "₹92 Cr", "₹138 Cr"][index - 1] ?? meridian.contractValue,
    workingDaysElapsed: 240 + index * 31,
    latestReport: {
      ...meridian.latestReport,
      id: `dpr-${summary.id}-2026-08-17`,
      projectId: summary.id,
      status: summary.reportStatus === "sent" ? "sent" : "draft",
      sentAt: summary.reportStatus === "sent" ? "18:10" : undefined,
      callsIncluded: summary.callsCompleted,
      callsExpected: summary.callsExpected,
      executiveSummary: `${summary.name} is ${Math.abs(summary.progress - summary.plannedProgress)}% ${summary.progress >= summary.plannedProgress ? "ahead of" : "behind"} plan. ${open} open issues require active follow-up, including ${summary.criticalIssues} critical item${summary.criticalIssues === 1 ? "" : "s"}.`,
    },
    team: meridian.team.slice(0, summary.callsExpected).map((person, personIndex) => ({
      ...person,
      id: `${summary.id}-p-${personIndex + 1}`,
      lastCallStatus: personIndex < summary.callsCompleted ? "completed" : "scheduled",
      lastCallAt: personIndex < summary.callsCompleted ? person.lastCallAt : "Scheduled",
    })),
    issues: meridian.issues.slice(0, Math.min(open, 3)).map((issue, issueIndex) => ({
      ...issue,
      id: `${summary.id}-iss-${issueIndex + 1}`,
      severity: issueIndex < summary.criticalIssues ? "critical" : issue.severity,
    })),
    calls: meridian.calls.slice(0, summary.callsCompleted).map((call, callIndex) => ({ ...call, id: `${summary.id}-call-${callIndex + 1}` })),
  };
}

const projectDetails: Record<string, ProjectDetail> = Object.fromEntries(
  projects.map((project, index) => [project.id, index === 0 ? meridian : projectFromTemplate(project, index)]),
);

export function getDemoProgram(): ProgramOverview {
  const totalProgress = projects.reduce((sum, project) => sum + project.progress, 0);
  return {
    projects,
    totalProjects: projects.length,
    activeSites: projects.length,
    portfolioProgress: Math.round(totalProgress / projects.length),
    callsCompleted: projects.reduce((sum, project) => sum + project.callsCompleted, 0),
    callsExpected: projects.reduce((sum, project) => sum + project.callsExpected, 0),
    openIssues: projects.reduce((sum, project) => sum + project.openIssues, 0),
    criticalIssues: projects.reduce((sum, project) => sum + project.criticalIssues, 0),
    reportsSent: projects.filter((project) => project.reportStatus === "sent").length,
    reportsExpected: projects.length,
    generatedAt: "17 August 2026 · 18:45 IST",
  };
}

export function getDemoProject(projectId: string): ProjectDetail | undefined {
  return projectDetails[projectId];
}

export function getAllDemoProjects(): ProjectDetail[] {
  return Object.values(projectDetails);
}
